filenames:
  - /var/log/auth.log
  - /var/log/syslog
  - /var/log/kern.log
  - /var/log/ufw.log
  - /var/log/mail.log
labels:
  type: syslog
---
filenames:
  - /var/logs/traefik/access.log
  - /var/logs/traefik/traefik.log
labels:
  type: traefik
---
source: docker
container_name:
 - auth
labels:
  type: authentik
